[[rocSPARSE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "297d9ba1d217f09e60053e6f2a6e37373265d837"
libc = "glibc"
os = "linux"

    [[rocSPARSE.download]]
    sha256 = "7293989ee295aea53d784db87d729ae6ae05f9fdcdad18e3be4f5a537076bb10"
    url = "https://github.com/JuliaBinaryWrappers/rocSPARSE_jll.jl/releases/download/rocSPARSE-v4.5.2+0/rocSPARSE.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[rocSPARSE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa49c71897707edc62f2817b46e315a084ea71ac"
libc = "musl"
os = "linux"

    [[rocSPARSE.download]]
    sha256 = "419634c8ece971263bf362dd0b12f955e05bb73b6c545e9274beeb639720c896"
    url = "https://github.com/JuliaBinaryWrappers/rocSPARSE_jll.jl/releases/download/rocSPARSE-v4.5.2+0/rocSPARSE.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"
